version: '3.2'
services:

  app_moodle:
    image: karimfadl/moodle-lms
    container_name: app_moodle
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./config/php/www.conf:/etc/php-fpm.d/www.conf
      - ./config/php/php.ini/:/etc/php.ini
      - ./config/ssl/:/etc/nginx/ssl/
      - ./moodle:/var/www/html:rw
      - ./moodledata:/var/moodledata:rw
    depends_on:
      - db_moodle
    environment:
      TZ: "Africa/Egypt"

  myadmin_moodle:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin_moodle
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db_moodle
    restart: always
    depends_on:
      - db_moodle
    environment:
      TZ: "Africa/Egypt"

  db_moodle:
    image: mariadb:10.4.3
    container_name: db_moodle
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'moodle'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      TZ: "Africa/Egypt"
    volumes:
      - ./db:/var/lib/mysql
      - /srv/docker/sockets/mariadb.container.sock:/var/run/mysqld/mysqld.sock
